name: flutter_movie_clean
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  data:
    path: data
  domain:
    path: domain
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  intl: ^0.18.0
  go_router: ^10.0.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.8

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

### FlutterGen configs
flutter_gen:
  output: lib/gen/
  line_length: 80
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

### Assets configs
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/strings/
    - assets/images/
    - assets/colors/
