name: flutter_movie_clean
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.8
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.0
  skeletonizer: ^0.7.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

### FlutterGen configs
flutter_gen:
  output: lib/gen/
  line_length: 80
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors

### Assets configs
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/strings/
    - assets/images/
    - assets/colors/
    - assets/images/welcomes/
    - assets/images/profile/
